INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Gerasim', 'Popov', '1994-11-28', 'Kazan');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Robert', 'Alexeev', '1974-1-5', 'Chelny');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Nikolay', 'Ivanov', '1985-6-27', 'Kazan');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Maksim', 'Michailov', '1995-4-14', 'Sviyazhsk');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Alexnder', 'Agapov', '1979-3-2', 'Kazan');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Marsel', 'Sidikov', '1994-2-19', 'Kazan');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Anton', 'Ivanov', '1986-11-28', 'Sviyazhsk');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Alexey', 'Nikolayev', '1975-9-3', 'Kazan');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Konstantin', 'Pavlov', '1982-8-7', 'Cheboksary');
INSERT INTO owners(first_name, last_name, date_of_birth, city) VALUES ('Konstantin', 'Vasilyev', '1993-5-12', 'Cheboksary');

INSERT INTO cars(mileage, colour) VALUES (12354, 'green');
INSERT INTO cars(mileage, colour) VALUES (89, 'blue');
INSERT INTO cars(mileage, colour) VALUES (9587, 'black');
INSERT INTO cars(mileage, colour) VALUES (59, 'white');
INSERT INTO cars(mileage, colour) VALUES (48, 'yellow');
INSERT INTO cars(mileage, colour) VALUES (37, 'orange');
INSERT INTO cars(mileage, colour) VALUES (126, 'brown');
INSERT INTO cars(mileage, colour) VALUES (364, 'green');
INSERT INTO cars(mileage, colour) VALUES (784, 'black');
INSERT INTO cars(mileage, colour) VALUES (1, 'silver');

INSERT INTO cars_owners(id_car, id_owner) VALUES (1, 1);
INSERT INTO cars_owners(id_car, id_owner) VALUES (2, 2);
INSERT INTO cars_owners(id_car, id_owner) VALUES (3, 3);
INSERT INTO cars_owners(id_car, id_owner) VALUES (4, 4);
INSERT INTO cars_owners(id_car, id_owner) VALUES (5, 5);
INSERT INTO cars_owners(id_car, id_owner) VALUES (6, 6);
INSERT INTO cars_owners(id_car, id_owner) VALUES (7, 7);
INSERT INTO cars_owners(id_car, id_owner) VALUES (8, 8);
INSERT INTO cars_owners(id_car, id_owner) VALUES (9, 9);
INSERT INTO cars_owners(id_car, id_owner) VALUES (10, 10);